version: '3.8'

services:
  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    restart: always
    ports:
      - "7474:7474"   # Conectarse desde la web
      - "7687:7687"   # Concetarse desde javascript
    environment:
      - NEO4J_AUTH=neo4j/test123
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
